### PR TITLE
debugged speech recognition

### PR DESCRIPTION
**Pull request by Yatish04**
Speech Recognition works now

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
Doesn't seem to be working on Windows. Can you check for Linux @kb-studios ? :smile:

**Comment by Yatish04** [comment]
I did try on windows. Can you send me the screenshot of traceback.

**Comment by kb-studios** [comment]
Stacktrace for linux - 
```
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Killed
```
Most answers for this error point out to issue with our program not being able to access the microphone server. The issue seems to be with pyAudio. I guess speech_recognition uses that. Maybe we can look for a workaround.

**Comment by Yatish04** [comment]
@kb-studios do you have pyAudio. U need that.

**Comment by Yatish04** [comment]
I can send a video of it working properly on windows

**Comment by kb-studios** [comment]
@Yatish04 Yes, I have pyAudio configured.:smiley:

**Comment by kb-studios** [comment]
The current code on the `master` branch, has speech recognition working for me. Was it not working? @Yatish04 Because it seems to be working fine on my Windows machine.

**Comment by Yatish04** [comment]
You had to press enter to record right?
screenshot 10

**Comment by kb-studios** [comment]
Yes @Yatish04, entering a blank string triggers the speech recognition

**Comment by Yatish04** [comment]
@the-ethan-hunt  @kb-studios  
https://drive.google.com/file/d/12GTga5Zh4lX0tUUlLzOIjPt3wiy9hlQI/view?usp=sharing

**Comment by Yatish04** [comment]
@kb-studios  the code on the master does not search. It  recognises and sets the value thats it

**Pull request merged**
