### PR TITLE
benji.py new feature and logo

### PR DESCRIPTION
**Pull request by Snehal-Reddy**
I added a feature to track a particular location using google maps .

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
Doesn't seem to be working, @Snehal-Reddy . B.E.N.J.I. is not executing the commands. Please check :smile:

**Comment by Snehal-Reddy** [comment]
The thing is I have a Mac and I am not able to make anything work . So I am
unable to check whether the features I added are working.

-K.Snehal Reddy

**Comment by the-ethan-hunt** [comment]
I request you before pulling a request to the main repository, please check it by running on your device. I suggest you to install a virtual machine to check out your changes

**Comment by Snehal-Reddy** [comment]
The latest commit is working , now .

**Comment by the-ethan-hunt** [comment]
@Snehal-Reddy your PR has conflicts. Please check them and debug your code. :smile:

**Comment by Snehal-Reddy** [comment]
Done ! :)

**Comment by Snehal-Reddy** [comment]
I even added the new logo in benji_final.ico

**Comment by the-ethan-hunt** [comment]
Great! Merging this PR!

**Pull request merged**
