### PR TITLE
New PR

### PR DESCRIPTION
**Pull request by rishabh0098**
Added feature for finding files in PC

### CODE REVIEW

**Comment by aniketgattani** [comment]
You should rename the PR i guess with a title which is more appropriate so that any new collaborator comes to know what all progress has been made in this project up till now.

**Comment by the-ethan-hunt** [comment]
@aniketgattani please stop posting review comments. This is the work of a maintainer. Not appreciated at all

**Comment by aniketgattani** [comment]
But it is supposed to be open source right. I actually started work on this issue but then found that there was already a PR waiting for this. Hence I thought it would be beneficial if the corresponding collaborator changes the PR name thats it.

**Comment by the-ethan-hunt** [comment]
@aniketgattani , there are some rules in open-source. There is one little but important rule that a contributor should **not** review a PR without the maintainer's permission. It is not appreciated.

@rishabh0098 , @abhimanyuthakre has found issues in the code. Please hear him out and debug the code ASAP

**Comment by aniketgattani** [comment]
@the-ethan-hunt sorry from my side. But I didnt even review this. My point was simple. Any new collaborator should get a clear idea what all other people are doing and hence an appropriate name for PR was necessary. I mentioned nothing abt the PR. I thought this would lead to the betterment of the project and hence I commented. Extremely sorry from my part. Won't be commenting anything next time onwards.

**Comment by the-ethan-hunt** [comment]
Merging this

**Comment by rishabh0098** [comment]
I think I'm getting much better with git
Thanks @the-ethan-hunt :+1:

**Pull request merged**
