### PR TITLE
Added the setup.py file

### PR DESCRIPTION
**Pull request by lapalb**
Added the `setup.py` file in the project. Have listed the dependencies

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
Nice try @lapalb ! Please correct the typo and the author data. You should take the name of the author and his GitHub profile differently. I suggest you take a look at this issue #47 where I have added a source. Correct these error and I will merge the PR!

**Comment by lapalb** [comment]
Added a separate field for author's GitHub profile

**Comment by the-ethan-hunt** [comment]
There are still typos :confused:

**Comment by lapalb** [comment]
Have corrected few typos, Please check.
`README.rst -> README.md`
`spelling of assistant`

**Comment by the-ethan-hunt** [comment]
Looks great! Merging this PR!

**Pull request merged**
