### PR TITLE
Issue #31 Modularizing Code - Srishilesh

### PR DESCRIPTION
**Pull request by srishilesh**
Issue #31 Modularizing code

I have modularized the code for the following events and commented at necessary places for better understanding
1) Translator
2) Lyrics 
3) Screen shot
4) Add user face
5) Upcoming events

Please note, I have commented out the code for Face Recognition, since I have an issue running it.
@the-ethan-hunt Please have a look at it and let me know how to proceed.

Issue maintained by srishilesh

### CODE REVIEW

**Comment by RajatGarg97** [comment]
Hi @srishilesh 
I am reviewing the changes. It might take sometime

**Comment by RajatGarg97** [comment]
Translator, Screenshot, and lyrics look good. I'll review the rest asap

**Comment by RajatGarg97** [comment]
Hi @srishilesh 
You have done a great job by modularising the code. But you haven't followed any directory structure all files are present in the same directory

**Comment by srishilesh** [comment]
> Hi @srishilesh
> You have done a great job by modularising the code. But you haven't followed any directory structure all files are present in the same directory

Thank you, I will modularize the remaining ASAP and follow the directory structure as you mentioned.

**Pull request merged**
