### PR TITLE
Secure and Calculator for linux

### PR DESCRIPTION
**Pull request by rohanricky**
The `ctypes.windll.user32.LockWorkStation()` is not executing for me. We could use a simpler subprocess module to do the same.

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
The calculator feature is not being opened. Similarly, the `cannot lock device` is being displayed. Correct the code to make these functions work

**Comment by rohanricky** [comment]
Did you check it on a VM? Because in Ubuntu 16.04 the code is working correctly.

**Comment by the-ethan-hunt** [comment]
Um, still no. Are you testing the code before committing?

**Comment by rohanricky** [comment]
out

**Pull request merged**
