### PR TITLE
Update README with working of B.E.N.J.I on Linux

### PR DESCRIPTION
**Pull request by kb-studios**
A video demonstration showing the working of B.E.N.J.I.

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
Looks great to me :tada:

**Comment by BrianMwangi21** [comment]
Can we have one for windows too ?

**Comment by the-ethan-hunt** [comment]
Yes, sure! But I will be able to merge your PR only tomorrow :sweat_smile:

**Comment by the-ethan-hunt** [comment]
New comment: How about a newcomer does that @BrianMwangi21 ? You can solve other issues. :smile:

**Comment by BrianMwangi21** [comment]
Sure. Someone else can do that. No problemo

**Pull request merged**
