### PR TITLE
readme updated with proper documentation for running in linux

### PR DESCRIPTION
**Pull request by nityanandagohain**

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
Can you please explain what changes you have made @nityanandagohain ?

**Comment by nityanandagohain** [comment]
i have added the prerequisites in the documentation which are need in linux .

**Comment by the-ethan-hunt** [comment]
You have just changed `python benji.py` to `python 3 benji.py`. That is just for python 3. I don't think we require this :smile:

**Comment by nityanandagohain** [comment]
plus i have add other things such as espeak,pyttsx3,libasound-dev, portaudio19-dev, libportaudio2, libportaudiocpp0 ,ffmpeg ,libav-tools

**Comment by the-ethan-hunt** [comment]
I understand that but the libraries you mentioned are already present in the `requirements.txt`. B.E.N.J.I. is working on that. I don't think we require any more libraries. :smile:

**Comment by nityanandagohain** [comment]
okey then  i am closing this pr ... :)

**Comment by the-ethan-hunt** [comment]
@nityanandagohain , you can solve other `good first issues`! They can help you get going

**Comment by nityanandagohain** [comment]
Sure thanks !

**Pull request closed without merging**
