### PR TITLE
Graph Creation 

### PR DESCRIPTION
**Pull request by Pratik-Sanghani**
Plotting of graph feature is added with respect to issue #3 .
Change in requirements for OpenCv login with Face.

### CODE REVIEW

**Comment by Pratik-Sanghani** [comment]
graph_benji

**Comment by the-ethan-hunt** [comment]
@abhimanyuthakre please review the opencv changes
@Pratik-Sanghani please update your fork

**Comment by abhimanyuthakre** [comment]
The changes for opencv looks good. But the updated version for facial recognition requires other libraries too. I have included 2 dependencies which I remember, in my PR. @the-ethan-hunt

**Comment by Pratik-Sanghani** [comment]
Conflicts removed. @the-ethan-hunt
dependencies added. @abhimanyuthakre

**Comment by the-ethan-hunt** [comment]
Merging this PR :+1:

**Pull request merged**
