### PR TITLE
Start Button Added

### PR DESCRIPTION
**Pull request by abhimanyuthakre**
Button is added. First it used to take only one query. Now it can take as many queries(without closing benji and reopening it).

### CODE REVIEW

**Comment by abhimanyuthakre** [comment]
And also, new query is displayed each time.

**Comment by BrianMwangi21** [comment]
the latest version is different to the version you are working on, i think

that part you edited for 'who are you' has been worked on. it now searches for keywords in the input from specific arrays. hence 'who are you' is similar to 'what is your name'

**Comment by the-ethan-hunt** [comment]
@abhimanyuthakre , please update your repo and then push the PR. :smile: .

**Comment by the-ethan-hunt** [comment]
@abhimanyuthakre , can you please explain the necessity of this button? :smile: 
When I input a command and B.E.N.J.I. obeys it, it also clears the space for another command. Why do we need a start button then?

**Comment by abhimanyuthakre** [comment]
I hadn't synced my repository when @BrianMwangi21 had made changes. Sorry for that. And at that time, I came up with the idea of adding a button. Thanks @BrianMwangi21

**Comment by BrianMwangi21** [comment]
You're always welcome @abhimanyuthakre

**Comment by the-ethan-hunt** [comment]
@abhimanyuthakre Your PR is having conflicts. You have duplicated the code. Please take the error out and then send the PR

**Comment by the-ethan-hunt** [comment]
Closing this PR

**Pull request closed without merging**
