### PR TITLE
Increased performance by adding new threads

### PR DESCRIPTION
**Pull request by Yatish04**
Gui doesnt hang now

### CODE REVIEW

**Comment by Yatish04** [comment]
Also in Linux version there are three arguments to be passed, frame put and link. But while passing only two are given. Frame is not given. That's why I made it global

**Comment by rohanricky** [comment]
So what we can do is define the global at the top and assign view = frame inside. Possible?

**Comment by the-ethan-hunt** [comment]
@rohanricky , this is the second time I am saying you *not* to review or approve the PR until requested by the mentor himself. This is not acceptable.

**Comment by the-ethan-hunt** [comment]
Please resolve your conflicts for merging

**Pull request closed without merging**
