### PR TITLE
Add docstrings

### LINKED ISSUE #136: Add Doctsrings: Improve Documentation
The project requires doc-strings support for the implemented functions and classes. It will help in an easier understanding of code for newcomers.
The best way is to follow the Python's PEP8 Docstring convention.
More details here: https://www.python.org/dev/peps/pep-0257/

### PR DESCRIPTION
**Pull request by agarwalrounak**
Fixes #136

### CODE REVIEW

**Comment by agarwalrounak** [comment]
@the-ethan-hunt please review!

**Comment by the-ethan-hunt** [comment]
@agarwalrounak citing this from the B.E.N.J.I. for students or mentees wiki:
> Do not ping your mentor repeatedly. He/She might be busy with other commitments too. If you think your mentor is not reviewing your PR, ping him/her in intervals of a week. If the mentor does not reply after two pings, ping the maintainer(me) straight away and I will review the PR.

It is requested not to repeat this again. 
Merging this PR.

**Comment by agarwalrounak** [comment]
It was the first time that I tagged you so I don't understand where `repeatedly` comes from. If this is interferring with your `other commitments` then I promise not to do that again.

**Comment by agarwalrounak** [comment]
It was the first time that I tagged you so I don't understand where `repeatedly` comes from. If this is interferring with your `other commitments` then I promise not to do that again.
Thanks a lot for merging this PR.

**Pull request merged**
