### PR TITLE
new translate feature

### PR DESCRIPTION
**Pull request by Snehal-Reddy**

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
Steps to do for you
1. Update your fork
2. Remove all indentation errors
3. Provide "how to use this feature" in FAQ section of `readme.md`

**Comment by the-ethan-hunt** [comment]
You can do your work here, no need to close this PR

**Comment by Snehal-Reddy** [comment]
ok ! thanks !

**Comment by Snehal-Reddy** [comment]
Finally , conflict-free ! :)

**Comment by the-ethan-hunt** [comment]
Your map feature is working. The translation one is not. Please check the problem. And please test your files before submitting a PR. I have to solve indentation problems every time I run your file

**Comment by Snehal-Reddy** [comment]
ok !

**Comment by the-ethan-hunt** [comment]
Um, still not working. Are you testing the translation feature before committing it?

**Comment by Snehal-Reddy** [comment]
Indentation fixed and translate feature working .

**Comment by Snehal-Reddy** [comment]
I will try afresh !

**Pull request closed without merging**
